### ISSUE TITLE
Using wildcards with braces

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [tmsvg/pear-tree#4]
So, I'm trying to add the following mapping (for [ReasonML's interpolated strings](https://bucklescript.github.io/docs/en/interop-cheatsheet#string-unicode-interpolation), that look something like `{bleh| this |bleh}`):

```viml
" ~/.vim/ftplugin/reason.vim
let b:pear_tree_pairs = extend(deepcopy(g:pear_tree_pairs), {
    \ '{*|': {'closer': '|*}'}
\ }, 'keep')
```

However, only `{` is getting paired — and I don't see a `<Plug>(PearTreeOpener_|)` mapping. Is this a bug, or am I mis-reading the docs?

**Comment by tmsvg** [comment]
The issue is that `|` is used in VimL to separate commands, so when Pear Tree tries to map it via an `execute` command, it creates invalid syntax. So basically, Pear Tree does not yet support `|` being the last character of an opener, but I'll have a fix ready soon. Thank you for bringing this to my attention.

**Comment by ELLIOTTCABLE** [comment]
🎉
